#!/usr/bin/env bash
#Bash script that will display information about subdomains.

# Function to query DNS records and display information
query_dns() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dns_result=$(nslookup -query=A "$sub.$domain" | grep "Address:" | awk '{ print $2 }')
        if [ -z "$dns_result" ]; then
            echo "The subdomain $sub is not found."
        else
            record_type="A record"
            echo "The subdomain $sub is a $record_type and points to $dns_result"
        fi
    done
}

# Check for the correct number of arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

# Call the query_dns function
query_dns "$domain" "$subdomain"
