#!/usr/bin/env bash
#Bash script that will display information about subdomains.
# Function to query DNS records and display information
query_dns() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short -t A "$sub.$domain" | awk '{ if (NF == 0) { print "No A record found" } else { print "A record" } }')
        destination=$(dig +short -t A "$sub.$domain")

        echo "The subdomain $sub is a $record_type and points to $destination"
    done
}

# Check for the correct number of arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

# Call the query_dns function
query_dns "$domain" "$subdomain"
