#!/usr/bin/env bash
# Script that transfers file to server

# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if less than 4 parameters are passed
if [ $# -lt 4 ]; then
    display_usage
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# SCP command to transfer file
scp_cmd="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/"

# Execute SCP command
$scp_cmd
