#!/usr/bin/env bash
# Installing nginx web server 

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
