#!/usr/bin/env bash
# Bash script to configure Nginx on server so that HTTP response 
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Define the custom Nginx configuration file
custom_config_file="/etc/nginx/sites-available/default"

# Get the hostname of the server
server_hostname=$(hostname)

# Create the custom Nginx configuration file
echo "server {" | sudo tee $custom_config_file
echo "    listen 80;" | sudo tee -a $custom_config_file
echo "    location / {" | sudo tee -a $custom_config_file
echo "        add_header X-Served-By $server_hostname;" | sudo tee -a $custom_config_file
echo "        # Your other Nginx configurations go here..." | sudo tee -a $custom_config_file
echo "    }" | sudo tee -a $custom_config_file
echo "}" | sudo tee -a $custom_config_file

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the custom configuration
sudo systemctl reload nginx

echo "Nginx has been configured with the custom HTTP response header 'X-Served-By'."
