#!/usr/bin/env bash
# Simplified bash script setting Nginx to listen on port 80.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

if systemctl is-active nginx | grep -q "inactive"; then
    systemctl start nginx
fi
