#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.

pid=$(pgrep -f "4-to_infinity_and_beyond")
if [[ -n $pid ]]; then
  # Send the SIGINT signal to terminate the process gracefully
  kill -SIGINT "$pid"
  echo "Successfully stopped the 4-to_infinity_and_beyond process."
else
  echo "The 4-to_infinity_and_beyond process is not currently running."
fi
