#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.

# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
  echo "The process is not running."
else
  # Send the TERM signal to the process
  echo "Stopping the process..."
  kill -s TERM "$pid"

  # Wait for the process to exit
  while [ -e "/proc/$pid" ]; do
    sleep 1
  done

  echo "The process has been stopped."
fi
