#!/usr/bin/env bash
#Bash script that displays o infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

 Function to handle SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}

# Register the SIGTERM signal handler
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
