#!/usr/bin/env bash
#Bash script that displays contents of current directory
#in list format
#showing only the part of the name after the first dash is displayed

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        filename="${file#*-}"  # extract the part after the first dash
        echo "$filename"
    fi
done
