#!/usr/bin/env bash
# Shorter bash script that configures Nginx to run as the nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx reload
ps aux | grep 'nginx: master process' | grep -q 'nginx: master process /usr/sbin/nginx' && nc -z 0 8080

