#!/usr/bin/env bash
# Generate an RSA key pair with a passphrase

erver_name="228879-web-01"
username="ubuntu"
ip="54.166.128.19"
private_key_name="school"
key_bits="4096"
passphrase="betty"

ssh-keygen -t rsa -b 4096 -f "school" -N "betty"
